Fix NoClassDefFoundError caused by horizontal class merging
Fixes: b/562960348
Change-Id: I93ba09c24c2e6854ef2b2227b84530bcfac45308
Cq-Exclude-Trybots: luci.r8.try:presubmit