Prevent crash when specifying resource only splits
According to the help, we should be able to pass nothing for jar inputs
or outputs for resource-only feature splits:
https://r8.googlesource.com/r8/+/refs/heads/main/src/main/java/com/android/tools/r8/R8CommandParser.java#121

However, when I tried this, it crashed:

java.lang.NullPointerException: Cannot invoke
"com.android.tools.r8.ProgramConsumer.getDataResourceConsumer()" because
the return value of "com.android.tools.r8.FeatureSplit.getProgramConsumer()"
is null
 at ...getDataResourceProvidersAndConsumers(FeatureSplitConfiguration.java:56)

The test I added reproduced this crash, and the test is now fixed.

Change-Id: If128ff7dec6ae77a082f5ac78c46df634a339eeb